homarr-labs/homarr

CODEOWNERS

chore: add codeowners (#378)

---

apps/nextjs/src/app/[locale]/manage/about/accordion.module.css
apps/nextjs/src/app/[locale]/manage/about/page.tsx
apps/nextjs/src/react-app-env.d.ts
apps/nextjs/src/versions/package-reader.ts
packages/translation/src/lang/en.ts

feat: add about page

---

Dockerfile

fix: sharp is not installed

---

package.json

fix: docker development path in package.json

---

apps/nextjs/src/app/[locale]/boards/(content)/_creator.tsx
apps/nextjs/src/app/[locale]/boards/[name]/layout.tsx
apps/nextjs/src/app/[locale]/boards/_layout-creator.tsx
packages/widgets/src/server/runner.tsx

fix: server data is loaded on settings page

---

.vscode/launch.json

config: add vscode launch profiles

---

packages/modals/src/index.tsx
packages/modals/src/reducer.tsx

fix: modal transition not working

---

apps/nextjs/src/components/user-avatar-menu.tsx
packages/modals/src/type.ts
packages/translation/src/lang/en.ts

feat: add login and logout

---

apps/nextjs/src/app/[locale]/manage/integrations/_integration-buttons.tsx
apps/nextjs/src/app/[locale]/manage/integrations/edit/[id]/_integration-edit-form.tsx
apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-dropdown.tsx
apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
apps/nextjs/src/app/[locale]/manage/integrations/page.tsx

fix: integration links in manage section do not work

---

apps/tasks/src/jobs/icons-updater.ts
apps/tasks/src/lib/cron-job/creator.ts

feat: add job on start option for icons updater

---

apps/nextjs/src/app/[locale]/manage/boards/page.tsx

feat: show creator on board page

---

apps/nextjs/src/app/[locale]/widgets/[kind]/_content.tsx
apps/nextjs/src/components/board/items/item-actions.tsx
apps/nextjs/src/components/board/sections/content.tsx
packages/validation/src/index.ts
packages/validation/src/shared.ts
packages/widgets/src/modals/widget-edit-modal.tsx

fix: unable to select integration on board page

---

apps/nextjs/src/app/[locale]/auth/invite/[id]/_registration-form.tsx
apps/nextjs/src/app/[locale]/auth/invite/[id]/page.tsx
apps/nextjs/src/app/[locale]/auth/login/_login-form.tsx
packages/api/src/router/test/user.spec.ts
packages/api/src/router/user.ts
packages/translation/src/lang/en.ts
packages/validation/src/user.ts

feat: add user invite registration

---

Dockerfile
packages/redis/redis.conf
scripts/run.sh

fix: rdb files can not be saved because of permission issues bug: redis can not save RDB files #318

---

package.json

config: fix db push command

---

apps/nextjs/src/app/[locale]/layout.tsx

fix: mantine react table style issue

---

apps/tasks/src/jobs/icons-updater.ts

fix: when no dead icons, all icons are removed

---

packages/redis/src/lib/channel.ts

feat: add redis cache channel

---

renovate.json5

config; activate automerge

---

tooling/prettier/index.mjs
turbo/generators/templates/package.json.hbs
turbo/generators/templates/tsconfig.json.hbs

config: format json hbs as json

---

.github/workflows/docker-image.yml

ci: use semver workflow action

---

.github/workflows/pr-conventional-commits.yml

ci: validate pr title

---

.github/workflows/code-quality.yml
vitest.config.ts

ci: report vitest code coverage

---

.github/workflows/conventional-commits.yml

config: add conventional commits workflow

---

.github/workflows/automatic-release.yml

ci: add automatic release workflow

---

.github/workflows/deployment-weekly-release.yml

fix: default branch for tag compare

---

.github/workflows/deployment-weekly-release.yml

ci: fix branch to compare tags

---

.github/workflows/deployment-weekly-release.yml

ci: fix fetch depth

---

.run/db_migration_mysql_generate.run.xml
.run/db_migration_sqlite_generate.run.xml
.run/db_push.run.xml
.run/db_studio.run.xml
.run/dev.run.xml
.run/docker_dev.run.xml
.run/format.run.xml
.run/format_fix.run.xml
.run/test.run.xml
.run/test_ui.run.xml

ci: add rider run configuration

---

.github/workflows/renovate-automatic-approval.yml

ci: use app instead of personal token

---

.vscode/settings.json

Note: TypeScript files are read-only https://github.com/lokalise/i18n-ally/wiki/Locale-Formats#supported-locale-formats
<br/>
</div>

chore: configure i18n ally

---

apps/nextjs/src/components/board/sections/gridstack/init-gridstack.ts
apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts

fix: gridstack not working

---

apps/tasks/eslint.config.js
apps/websocket/eslint.config.js
packages/widgets/src/clock/component.tsx

feat: Clock widget scalability

---

packages/api/src/router/user.ts

feat: improve user init setup

---

packages/translation/src/lang/en.ts
packages/widgets/src/dns-hole/summary/component.tsx

feat: DNS Hole summary Scalability

---

apps/tasks/package.json
apps/tasks/src/jobs.ts
apps/tasks/src/jobs/integrations/home-assistant.ts
packages/api/package.json
packages/api/src/middlewares/integration.ts
packages/api/src/router/integration.ts
packages/api/src/router/test/integration.spec.ts
packages/api/src/router/widgets/index.ts
packages/api/src/router/widgets/smart-home.ts
packages/common/src/encryption.ts
packages/common/src/index.ts
packages/common/src/number.ts
packages/common/src/url.ts
packages/definitions/src/integration.ts
packages/definitions/src/widget.ts
packages/integrations/package.json
packages/integrations/src/homeassistant/homeassistant-integration.ts
packages/integrations/src/homeassistant/homeassistant-types.ts
packages/integrations/src/index.ts
packages/redis/src/index.ts
packages/translation/src/lang/en.ts
packages/widgets/package.json
packages/widgets/src/index.tsx
packages/widgets/src/smart-home/entity-state/component.tsx
packages/widgets/src/smart-home/entity-state/index.ts
packages/widgets/src/smart-home/execute-automation/component.tsx
packages/widgets/src/smart-home/execute-automation/index.ts
pnpm-lock.yaml

feat: add homeassistant integration

---

apps/nextjs/src/app/[locale]/auth/login/_login-form.tsx
apps/nextjs/src/components/user-avatar-menu.tsx

fix: login with revalidate path and wrong preferences link

---

turbo.json

chore: change turbo ui to stream because the other one is unusable

---

apps/nextjs/src/components/icons/picker/icon-picker.tsx

fix: icon selector is a select not an autocomplete #515

---

apps/nextjs/src/app/[locale]/manage/apps/_form.tsx
apps/nextjs/src/app/[locale]/manage/apps/new/page.tsx
apps/nextjs/src/app/[locale]/manage/apps/page.tsx
apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-dropdown.tsx
apps/nextjs/src/components/icons/picker/icon-picker.tsx
packages/translation/src/lang/en.ts

fix: missing translations for apps / integrations #438

---

apps/nextjs/src/components/layout/navigation-link.tsx

fix: open navigation item by default

---

.github/workflows/deployment-weekly-release.yml

fix: typo in automatic release commit message

---

apps/tasks/src/jobs/integrations/media-organizer.ts
packages/api/src/middlewares/integration.ts
packages/api/src/router/widgets/calendar.ts
packages/integrations/src/base/creator.ts
packages/integrations/src/calendar-types.ts
packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
packages/widgets/src/calendar/calendar-event-list.tsx
packages/widgets/src/calendar/calender-day.tsx
packages/widgets/src/calendar/component.tsx
packages/widgets/src/calendar/serverData.ts

feat: improve calendar ux/ui

---

apps/nextjs/src/app/[locale]/manage/about/page.tsx
apps/nextjs/src/app/[locale]/manage/apps/edit/[id]/page.tsx
apps/nextjs/src/app/[locale]/manage/apps/new/page.tsx
apps/nextjs/src/app/[locale]/manage/apps/page.tsx
apps/nextjs/src/app/[locale]/manage/boards/page.tsx
apps/nextjs/src/app/[locale]/manage/integrations/edit/[id]/page.tsx
apps/nextjs/src/app/[locale]/manage/integrations/new/page.tsx
apps/nextjs/src/app/[locale]/manage/integrations/page.tsx
apps/nextjs/src/app/[locale]/manage/page.tsx
apps/nextjs/src/app/[locale]/manage/settings/page.tsx
apps/nextjs/src/app/[locale]/manage/tools/docker/page.tsx
apps/nextjs/src/app/[locale]/manage/tools/logs/page.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/layout.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/security/page.tsx
apps/nextjs/src/app/[locale]/manage/users/create/page.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/page.tsx
apps/nextjs/src/app/[locale]/manage/users/invites/page.tsx
apps/nextjs/src/app/[locale]/manage/users/page.tsx
apps/nextjs/src/components/navigation/dynamic-breadcrumb.tsx
packages/translation/src/index.ts
packages/translation/src/lang.ts
packages/translation/src/lang/en.ts

feat: add dynamic breadcrumb

---

tooling/github/setup/action.yml

<br/>
</div>
Fixes:
For https://github.com/homarr-labs/homarr/pull/739

chore(deps): update pnpm/action-setup to v4

---

.vscode/settings.json
apps/nextjs/src/components/board/sections/content.tsx
packages/api/src/router/widgets/calendar.ts
packages/api/src/router/widgets/index.ts
packages/api/src/router/widgets/media-server.ts
packages/cron-jobs/src/index.ts
packages/cron-jobs/src/jobs/integrations/media-organizer.ts
packages/cron-jobs/src/jobs/integrations/media-server.ts
packages/definitions/src/widget.ts
packages/integrations/package.json
packages/integrations/src/base/creator.ts
packages/integrations/src/index.ts
packages/integrations/src/interfaces/media-server/session.ts
packages/integrations/src/jellyfin/jellyfin-integration.ts
packages/redis/package.json
packages/redis/src/index.ts
packages/redis/src/lib/channel.ts
packages/translation/src/lang/en.ts
packages/widgets/package.json
packages/widgets/src/calendar/serverData.ts
packages/widgets/src/index.tsx
packages/widgets/src/media-server/component.tsx
packages/widgets/src/media-server/index.ts
packages/widgets/src/media-server/serverData.ts
pnpm-lock.yaml

feat: add jellyfin integration

---

packages/api/src/router/cron-jobs.ts
packages/api/src/router/log.ts
packages/api/src/router/widgets/app.ts
packages/api/src/router/widgets/media-server.ts
packages/api/src/router/widgets/smart-home.ts
packages/redis/src/lib/channel-subscription-tracker.ts
packages/redis/src/lib/channel.ts
packages/redis/src/lib/subscription-manager.ts

fix: memory leak caused by many unclosed redis subscriptions

---

apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
apps/nextjs/src/app/[locale]/manage/tools/docker/page.tsx
packages/api/src/router/docker/docker-router.ts
packages/api/src/router/docker/docker-singleton.ts
packages/translation/src/lang/en.ts

feat: add docker actions

---

apps/nextjs/src/app/[locale]/manage/page.tsx

fix: manage links wrong

---

.github/workflows/deployment-weekly-release.yml

fix: correctly set pr description

---

apps/websocket/package.json

fix: docker build

---

.github/workflows/deployment-weekly-release.yml

refactor: use gh cli to create pr

---

packages/integrations/src/overseerr/overseerr-integration.ts
packages/widgets/src/media-requests/stats/component.module.css
packages/widgets/src/media-requests/stats/component.tsx

feat: media request stats widget

---

apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
packages/translation/src/lang/en.ts

feat: allow no secrets for integration

---

apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/jobs-list.tsx

fix: job translations

---

.github/workflows/deployment-docker-image.yml
Dockerfile
apps/nextjs/next.config.mjs
development/docker-run.cmd
package.json
packages/log/src/index.mjs
packages/redis/src/lib/connection.ts
turbo.json

fix: deployment pipeline for docker not working

---

apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
apps/nextjs/src/app/[locale]/manage/users/_components/user-list.tsx
apps/nextjs/src/app/[locale]/manage/users/invites/_components/invite-list.tsx
packages/translation/package.json
packages/translation/src/lang/de.ts
packages/translation/src/lang/en.ts
packages/ui/package.json
packages/ui/src/hooks/index.ts
packages/ui/src/hooks/use-translated-mantine-react-table.ts
packages/widgets/src/media-server/component.tsx
pnpm-lock.yaml

fix: mantine-react-table not localized #333

---

apps/nextjs/src/app/[locale]/manage/users/[userId]/layout.tsx
packages/translation/src/lang/en.ts

fix: missing breadcrumb translation, wrong spacing in user layout

---

apps/nextjs/src/components/layout/background.tsx

fix: videos not playing automatically on iOS / mobile

---

packages/validation/src/form/i18n.ts
packages/validation/src/location.ts
packages/widgets/src/_inputs/widget-location-input.tsx
packages/widgets/src/modals/widget-edit-modal.tsx
packages/widgets/src/options.ts

feat: add validation to widget edit modal inputs

---

packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts

fix: overview in series of sonarr schema is optional

---

packages/widgets/src/dns-hole/controls/component.tsx
packages/widgets/src/dns-hole/controls/index.ts
packages/widgets/src/dns-hole/controls/serverData.ts
packages/widgets/src/dns-hole/summary/component.tsx
packages/widgets/src/dns-hole/summary/serverData.ts

fix: Fix typecheck, lint issues and errors brought to dnshole summary.

---

apps/nextjs/src/app/[locale]/manage/tools/docker/page.tsx
packages/api/src/router/docker/docker-router.ts
packages/api/src/router/test/docker/docker-router.spec.ts

fix: restrict access to docker containers page to admins

---

apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
packages/api/src/router/docker/docker-router.ts
packages/translation/src/lang/en.ts

<br/>
</div>
Also added a title attribute to the text of the image:

feat: add refresh button to docker containers table

---

apps/nextjs/src/components/icons/picker/icon-picker.tsx

feat: add preview to icon picker

---

packages/api/src/router/widgets/dns-hole.ts
packages/integrations/src/adguard-home/adguard-home-integration.ts
packages/integrations/src/adguard-home/adguard-home-types.ts
packages/integrations/src/base/creator.ts
packages/integrations/src/index.ts

feat: AdGuard Home integration

---

packages/cron-jobs-core/src/creator.ts
packages/cron-jobs/src/jobs/ping.ts
packages/redis/src/lib/channel.ts

fix: ping urls are not reset when restarting

---

apps/nextjs/src/components/board/items/item-actions.tsx
apps/nextjs/src/components/board/sections/content.tsx
packages/translation/src/lang/en.ts

feat: add duplication action for items

---

apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx

fix: alert that certain fields in user settings are disabled is always shown

---

.github/workflows/renovate-automatic-approval.yml

fix: github actor name for automatic approval wrong

---

packages/widgets/src/modals/widget-edit-modal.tsx
packages/widgets/src/options.ts

feat: change visibility in item options based on selected integration kinds

---

apps/nextjs/src/app/[locale]/auth/login/page.tsx

fix: redirect url from login not working

---

apps/nextjs/src/app/[locale]/manage/boards/_components/create-board-button.tsx
apps/nextjs/src/components/manage/boards/add-board-modal.tsx
packages/api/src/router/board.ts
packages/api/src/router/test/board.spec.ts
packages/translation/src/lang/en.ts
packages/validation/src/board.ts

feat: add column count and is public options to board creation modal

---

.github/workflows/renovate-automatic-approval.yml

fix: wrong id for renovate auto approval

---

apps/nextjs/src/app/[locale]/auth/login/_login-form.tsx
packages/translation/src/lang/en.ts

feat: add collapse to login screen with cli command for password reset

---

apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx

refactor: remove item import for now

---

.github/workflows/deployment-docker-image.yml
Dockerfile

<br/>
</div>
This will publish an artifact for arm64.
Thanks you https://gist.github.com/ijpatricio/fe3ea4029743a209a70358181144a267

feat: support arm64

---

packages/widgets/src/dns-hole/controls/component.tsx

fix: dns-hole controls display on  safari

---

.github/workflows/deployment-docker-image.yml

fix: workflow inputs and docker push

---

Dockerfile
apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx
nginx.conf
scripts/run.sh

<br/>
</div>
Depends on #1072 (After merging 1072, path for websocket server has to be adjusted to `/websockets`)
Closes #904

feat: add nginx proxy

---

apps/nextjs/src/env.mjs

fix: db port validation for env variable wrong

---

Dockerfile
development/docker-run.cmd

ci: fix issue with pnpm installation

---

packages/api/src/router/widgets/dns-hole.ts
packages/api/src/router/widgets/downloads.ts
packages/cron-jobs/src/index.ts
packages/cron-jobs/src/jobs/integrations/dns-hole.ts
packages/cron-jobs/src/jobs/integrations/dnsHole.ts
packages/integrations/src/adguard-home/adguard-home-integration.ts
packages/integrations/src/interfaces/dns-hole-summary/dns-hole-summary-types.ts
packages/integrations/src/types.ts
packages/translation/src/lang/en.ts
packages/widgets/src/dns-hole/controls/component.tsx
packages/widgets/src/dns-hole/controls/index.ts
packages/widgets/src/dns-hole/controls/serverData.ts
packages/widgets/src/dns-hole/summary/component.tsx
packages/widgets/src/dns-hole/summary/index.ts
packages/widgets/src/dns-hole/summary/serverData.ts
packages/widgets/src/downloads/component.tsx
packages/widgets/src/widgets-common.css

Feature parity with oldmarr: 
ScrollArea with content at bottom.
Processing state when toggling
fix: Controls widget looks
feat: advanced control management (with permissions)
feat: disconnected state (Both widgets)
fix: summary widget sizing
feat: summary text flash on update
[Screencast from 2024-09-17 22-20-23.webm](https://github.com/user-attachments/assets/aa25188a-37a6-459e-9b31-4615884bd430)

feat: DnsHole feature parity with oldmarr

---

scripts/run.sh

<br/>
</div>
This will be especially useful for help charts

feat: add env variable to disable db migrations on startup

---

packages/spotlight/src/components/spotlight.tsx
packages/spotlight/src/modes/index.tsx

fix(spotlight): x button not clickable, help links open in current tab, bad screen usage on mobile

---

apps/tasks/src/undici-log-agent-override.ts

fix: sensitive data can be leaked through query parameters

---

packages/auth/configuration.ts
packages/auth/providers/credentials/authorization/ldap-authorization.ts
packages/auth/providers/test/ldap-authorization.spec.ts

<br/>
</div>
Implements the ldap part for #708

feat: add member sync between groups of ldap and homarr

---

apps/nextjs/src/app/[locale]/manage/users/_components/user-list.tsx
apps/nextjs/src/app/[locale]/manage/users/create/page.tsx
apps/nextjs/src/app/[locale]/manage/users/page.tsx

<br/>
</div>
Resolves https://discord.com/channels/972958686051962910/1267087145483370539

fix: it was possible to go to the create user page when credentials login disabled

---

apps/nextjs/src/app/[locale]/manage/users/_components/user-list.tsx
packages/translation/src/lang/en.ts

fix: email verified check is in a newline in users table

---

apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts

fix: new sections without add and change listeners

---

Dockerfile

chore: revert base image to 20.17.0 alpine

---

packages/widgets/src/notebook/default-content.ts

fix(notebook): default-content image path

---

apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
apps/nextjs/src/app/[locale]/layout.tsx
apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/page.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/page.tsx
apps/nextjs/src/components/layout/header/search.tsx
packages/spotlight/src/components/spotlight.tsx
packages/translation/src/lang/en.ts
packages/widgets/src/app/component.tsx
packages/widgets/src/dns-hole/summary/component.tsx
packages/widgets/src/downloads/component.tsx
packages/widgets/src/media-requests/stats/component.tsx
packages/widgets/src/weather/icon.tsx

fix: rtl common translation unnecessary

---

packages/validation/src/group.ts

fix: groups can be created with empty names

---

packages/auth/configuration.ts

fix: credentials auth not working

---

apps/nextjs/src/app/[locale]/manage/integrations/page.tsx

fix: integration actions hidden for full access users

---

packages/translation/src/lang/en.ts
packages/widgets/src/_inputs/widget-app-input.tsx
packages/widgets/src/options.ts
packages/widgets/src/widget-integration-select.tsx

feat: add notes for creation of apps and integrations in widget edit modal

---

.env.example
packages/auth/configuration.ts

<br/>
</div>
For https it would use `__Secure-authjs.session-token`

fix: inconsistent session cookie

---

apps/nextjs/src/app/[locale]/boards/(content)/_creator.tsx
apps/nextjs/src/app/[locale]/layout.tsx

feat: improve metadata

---

apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx

fix: local websocket url wrong

---

apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx

fix: color scheme manager should use cookie and not session value

---

Dockerfile
package.json

fix: docker build not working

---

packages/auth/events.ts

feat: #511 log user logged in

---

.gitattributes
tooling/prettier/index.mjs

chore: use consistent line ending

---

packages/cron-jobs/src/jobs/icons-updater.ts
packages/icons/package.json
packages/icons/src/icons-fetcher.ts
packages/icons/src/repositories/github.icon-repository.ts
packages/icons/src/repositories/jsdelivr.icon-repository.ts
packages/icons/src/repositories/local.icon-repository.ts
packages/icons/src/types/repository-icon.ts
pnpm-lock.yaml

feat: #1408 add local icon repository

---

apps/nextjs/src/app/api/auth/[...nextauth]/route.ts
packages/auth/configuration.ts
packages/auth/index.ts
packages/auth/next.ts

Same problem as https://github.com/ajnart/homarr/pull/2177, but next-auth is a little smarter
<br/>
</div>

fix: credentials login not working cause of cookie secure flag not possible for http

---

Dockerfile
scripts/run.sh

fix: adding volume /appdata removes created directories

---

packages/old-import/src/widgets/definitions/weather.ts
packages/old-import/src/widgets/options.ts
packages/translation/src/lang/en.json
packages/widgets/src/weather/component.tsx
packages/widgets/src/weather/icon.tsx
packages/widgets/src/weather/index.ts

feat: date format on weather widget

---

apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx

fix: websockets on https do not work

---

packages/spotlight/src/modes/command/index.tsx

fix: actions user has no permission to are shown in spotlight

---

packages/widgets/src/notebook/notebook.tsx

fix: notebook save button on block quote button

---

apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts

<br/>
</div>
Same issue as #1230

fix: items can not be placed in newly created dynamic section without saving

---

apps/nextjs/src/app/[locale]/manage/users/create/_components/create-user-stepper.tsx
apps/nextjs/src/app/[locale]/manage/users/create/page.tsx
apps/nextjs/src/components/access/group-select-modal.tsx
packages/api/src/router/group.ts
packages/api/src/router/user.ts
packages/translation/src/lang/en.json
packages/validation/src/user.ts

feat: add permission section to create user page

---

packages/auth/adapter.ts

fix: auth broken cause of consistent table column rename

---

apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/_add-group-member.tsx
apps/nextjs/src/components/access/user-select-modal.tsx
packages/api/src/router/user.ts

fix: external users can be added to groups manually

---

apps/nextjs/src/app/[locale]/boards/[name]/settings/page.tsx
apps/nextjs/src/app/[locale]/manage/settings/_components/board-settings-form.tsx
packages/api/src/router/board.ts
packages/api/src/router/test/board.spec.ts
packages/server-settings/src/index.ts
packages/translation/src/lang/en.json

fix: rename default to home board

---

apps/nextjs/src/app/[locale]/manage/users/groups/[id]/_transfer-group-ownership.tsx

fix: transfer group not invalidating path

---

apps/nextjs/src/app/[locale]/manage/apps/page.tsx
apps/nextjs/src/app/[locale]/manage/integrations/page.tsx
apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
apps/nextjs/src/components/no-results.tsx
packages/translation/src/lang/en.json

refactor: improve design of no integrations found

---

apps/nextjs/src/components/board/sections/category/actions/move-category.ts
apps/nextjs/src/components/board/sections/category/actions/test/move-category.spec.ts
apps/nextjs/src/components/board/sections/category/category-actions.ts

<br/>
</div>
**Before**
**After**

fix: moving categories up and down is not working

---

apps/nextjs/src/app/api/[...trpc]/route.ts
packages/api/src/router/user.ts
packages/api/src/test/open-api.spec.ts
packages/validation/src/user.ts

<br/>
</div>
Originally posted issue on Discord:
> Hi,
> I am making a script to delete apps using curl commands 
> 
> When trying to use the delete endpoint 
> `curl -vvv -X 'DELETE' \
>         "http://localhost:7575/api/apps/ob6o2080w0oje71bq0xmfulh" \
>         -H 'accept: application/json' \
>         -H 'ApiKey: <api-key>'`
> 
> I get the following error:
> 
>  ` Trying 127.0.0.1:7575...
> * Connected to localhost (127.0.0.1) port 7575 (#0)
> > DELETE /api/apps/ob6o2080w0oje71bq0xmfulh HTTP/1.1
> > Host: localhost:7575
> > User-Agent: curl/7.81.0
> > accept: application/json
> > ApiKey: <api-key>
> >
> * Mark bundle as not supporting …

fix: open-api doc generation failing, post patch and delete not exported

---

packages/common/src/url.ts
packages/integrations/src/adguard-home/adguard-home-integration.ts
packages/integrations/src/base/integration.ts
packages/integrations/src/download-client/deluge/deluge-integration.ts
packages/integrations/src/download-client/nzbget/nzbget-integration.ts
packages/integrations/src/download-client/qbittorrent/qbittorrent-integration.ts
packages/integrations/src/download-client/sabnzbd/sabnzbd-integration.ts
packages/integrations/src/download-client/transmission/transmission-integration.ts
packages/integrations/src/homeassistant/homeassistant-integration.ts
packages/integrations/src/jellyfin/jellyfin-integration.ts
packages/integrations/src/media-organizer/lidarr/lidarr-integration.ts
packages/integrations/src/media-organizer/radarr/radarr-integration.ts
packages/integrations/src/media-organizer/readarr/readarr-integration.ts
packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
packages/integrations/src/openmediavault/openmediavault-integration.ts
packages/integrations/src/overseerr/overseerr-integration.ts
packages/integrations/src/pi-hole/pi-hole-integration.ts
packages/integrations/src/plex/plex-integration.ts
packages/integrations/src/prowlarr/prowlarr-integration.ts

fix: trailing slash integration url issues

---

apps/nextjs/package.json
pnpm-lock.yaml

<br/>
</div>
I tested all basic functionallities like dynamic sections, moving items arround and resizing them with the new version

fix(deps): update gridstack.js fork to v1.11.2

---

.github/workflows/crowdin-schedule-download.yml
.github/workflows/crowdin-upload.yml
crowdin.yml

feat: integrate crowdin #1402

---

.github/workflows/automatic-approval.yml
.github/workflows/crowdin-schedule-download.yml
crowdin.yml

ci: add auto-merge after crowdin download and automatic approval

---

packages/api/src/router/update-checker.ts
packages/cron-jobs/src/jobs/update-checker.ts
packages/request-handler/src/update-checker.ts

feat: add update indicator

---

apps/nextjs/src/app/[locale]/manage/_components/hero-banner.module.css
apps/nextjs/src/app/[locale]/manage/_components/hero-banner.tsx
apps/nextjs/src/app/[locale]/manage/apps/page.tsx
apps/nextjs/src/app/[locale]/manage/boards/page.tsx
apps/nextjs/src/app/[locale]/manage/integrations/_components/secrets/integration-secret-card.tsx
apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/jobs-list.tsx
apps/nextjs/src/app/[locale]/manage/users/create/_components/create-user-stepper.tsx
apps/nextjs/src/components/icons/picker/icon-picker.tsx

fix: styles for light mode

---

apps/nextjs/src/components/board/items/item-content.tsx
packages/widgets/src/dns-hole/controls/component.tsx
packages/widgets/src/dns-hole/summary/component.tsx
packages/widgets/src/downloads/component.tsx
packages/widgets/src/health-monitoring/component.tsx
packages/widgets/src/indexer-manager/component.tsx
packages/widgets/src/media-requests/list/component.tsx
packages/widgets/src/media-requests/stats/component.tsx
packages/widgets/src/smart-home/entity-state/component.tsx

fix: trpc error at least one integration

---

.github/workflows/crowdin-schedule-download.yml

fix: auto-merge for crowdin download pull request not working

---

.github/workflows/crowdin-schedule-download.yml

fix: auto-merge crowdin pr not working

---

apps/nextjs/src/components/icons/picker/icon-picker.module.css
apps/nextjs/src/components/icons/picker/icon-picker.tsx

fix: icon picker keyboard interactions

---

apps/nextjs/src/app/[locale]/boards/[name]/settings/page.tsx
apps/nextjs/src/app/[locale]/manage/settings/page.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/page.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/page.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/permissions/page.tsx
packages/api/src/router/board.ts
packages/api/src/router/invite.ts
packages/api/src/router/serverSettings.ts
packages/api/src/router/test/invite.spec.ts
packages/api/src/router/test/serverSettings.spec.ts
packages/api/src/router/update-checker.ts
packages/api/src/router/widgets/dns-hole.ts
packages/api/src/router/widgets/indexer-manager.ts
packages/api/src/router/widgets/notebook.ts
packages/api/src/router/widgets/smart-home.ts

fix: issues found in security audit

---

packages/integrations/test/nzbget.spec.ts
packages/integrations/test/sabnzbd.spec.ts

test: reduce flakiness of nzbget and sabnzbd

---

LICENSE

docs: update license to apache 2.0

---

.github/workflows/deployment-docker-image.yml

fix: change docker concurrency group to allow multiple deployments to different branches

---

.github/workflows/deployment-docker-image.yml

fix: change permission for github action to contents write

---

.github/workflows/deployment-docker-image.yml

fix: add persists credentials false to checkout of release pipeline

---

.github/workflows/deployment-docker-image.yml

ci: add beta image tag for all beta releases

---

apps/nextjs/src/versions/package-reader.ts

fix: about version reads nextjs package-json

---

packages/definitions/src/group.ts

fix: conflicts between common admin group for ldap or oidc and credentials default group

---

.github/workflows/deployment-docker-image.yml
Dockerfile
scripts/entrypoint.sh
scripts/run.sh

<br/>
</div>
It runs the entrypoint as root to create the two directories in the volume, after that it runs the application itself as nextjs
```
PID   USER     TIME  COMMAND
1 root      0:00 {entrypoint.sh} /bin/sh /app/entrypoint.sh sh run.sh
10 nextjs    0:00 sh run.sh
21 nextjs    0:00 nginx: master process nginx -g daemon off;
22 nextjs    0:00 redis-server *:6379
23 nextjs    0:04 node apps/tasks/tasks.cjs
24 nextjs    0:01 node apps/websocket/wssServer.cjs
25 nextjs    0:00 next-server (v14.2.20)
26 nextjs    0:00 nginx: worker process
```
Closes #1699

fix: docker statup permission issue

---

.github/workflows/deployment-docker-image.yml

fix: update of dev branch has no credentials

---

.github/workflows/deployment-docker-image.yml

fix: about version is one behind because of missing package-json update in deploy

---

docs/README.md

docs: update crowdin badge to new translation project

---

apps/nextjs/src/app/[locale]/manage/medias/_actions/copy-media.tsx

fix: copy media link

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/integration.yml
.github/ISSUE_TEMPLATE/widget.yml

chore: update issue templates

---

packages/api/package.json
packages/api/src/router/medias/media-router.ts
packages/icons/package.json
packages/icons/src/local.ts
packages/icons/src/repositories/local.icon-repository.ts
pnpm-lock.yaml

fix(icons): local icon repository does not work with medias

---

.github/workflows/deployment-docker-image.yml
nginx.conf
packages/auth/providers/oidc/oidc-provider.ts
packages/auth/redirect.ts
packages/common/src/url.ts

fix(auth): oidc redirect does not respect https protocol

---

packages/api/src/router/group.ts

fix(onboard): missing admin permission assignment for external group

---

apps/nextjs/src/components/board/sections/item.module.css

fix(board): item background and border overridden by mantine card styles

---

packages/old-import/src/mappers/map-user.ts

<br/>
</div>
Closes https://github.com/ajnart/homarr/issues/2230

fix: oldmarr import user casing wrong

---

packages/common/src/types.ts
packages/old-import/src/import-items.ts
packages/old-import/src/mappers/map-item.ts
packages/old-import/src/widgets/definitions/index.ts
packages/old-import/src/widgets/options.ts

refactor: revert assignment of oldmarr widget mapping

---

apps/nextjs/src/env.mjs
packages/api/src/client.ts
turbo.json
vercel.json

chore(env): remove unused vercel-url env variable

---

packages/translation/src/lang/en.json
packages/widgets/src/health-monitoring/component.tsx

fix(health-monitoring): add months to uptime, fix status update

---

apps/nextjs/src/app/[locale]/auth/invite/[id]/page.tsx
apps/nextjs/src/app/[locale]/auth/login/page.tsx

fix: login page in light mode is always black

---

apps/nextjs/src/app/[locale]/manage/boards/_components/create-board-button.tsx

feat: remove import beta badge

---

apps/nextjs/src/app/[locale]/manage/boards/_components/board-card-menu-dropdown.tsx
packages/api/src/router/board.ts
packages/modals-collection/src/boards/duplicate-board-modal.tsx
packages/modals-collection/src/boards/index.ts
packages/translation/src/lang/en.json
packages/validation/src/board.ts

feat(board): add board duplication

---

Dockerfile

refactor: remove sharp image optimization

---

apps/nextjs/src/app/[locale]/manage/medias/_actions/upload-media.tsx
apps/nextjs/src/app/[locale]/manage/medias/page.tsx
apps/nextjs/src/components/icons/picker/icon-picker.tsx

feat(icons): add upload button to icon picker

---

apps/nextjs/src/components/board/items/item-content.tsx

fix(iframe): remove second scrollbar from item card

---

apps/nextjs/src/app/[locale]/manage/apps/page.tsx
apps/nextjs/src/app/[locale]/manage/medias/page.tsx
apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/page.tsx
packages/api/src/router/app.ts
packages/common/src/types.ts
packages/translation/src/lang/en.json

feat(app): add search and pagination

---

Dockerfile
apps/nextjs/next.config.ts

chore(config): change next-config from mjs to typescript

---

packages/translation/src/lang/en.json
packages/widgets/src/dns-hole/summary/component.tsx

fix(dns-hole-summary): calculation for domains and percentage for multiple integrations

---

packages/api/src/client.ts

fix: trpc removed export anything from client in react-query

---

packages/widgets/src/app/component.tsx

<br/>
</div>
Closes https://github.com/ajnart/homarr/issues/1933

fix(app): missing noreferer attribute for anchor tag

---

packages/integrations/src/interfaces/media-requests/media-request.ts

fix(media-request): media and media-request status can have missing values

---

.github/renovate.json5
apps/websocket/package.json
packages/api/package.json
pnpm-lock.yaml

fix: websockets not working extend not defined

---

packages/api/src/router/board.ts
packages/api/src/router/integration/integration-router.ts
packages/cron-jobs/src/jobs/icons-updater.ts
packages/db/driver.ts
packages/db/index.ts
packages/db/transactions.ts
packages/old-import/src/import/collections/common.ts
packages/old-import/src/import/import-initial-oldmarr.ts
packages/old-import/src/import/import-single-oldmarr.ts

<br/>
</div>
I know that this is not a great solution (writing the code twice) but I don't think we have a good alternative right now. In the long term we might want to consider moving from better-sqlite3 to `libsql`

fix: mysql transactions do not work with run property of sqlite

---

.github/workflows/deployment-weekly-release.yml

ci: change weekly release base to main branch

---

.github/ISSUE_TEMPLATE/bug_report.yml

chore: add version 1.0.0 to bug issue template

---

apps/nextjs/src/app/[locale]/manage/layout.tsx
packages/auth/providers/credentials/authorization/ldap-authorization.ts
packages/old-import/src/mappers/map-integration.ts

chore: Change icon and issue link to new repo in layout.tsx and index.tsx

---

docs/README.md

Changed installation and translation URLs
<br/>
</div>

chore: Fixed broken links in README.md

---

packages/api/src/router/user.ts

fix: unable to change home board in user preferences

---

apps/nextjs/src/components/board/items/item-content.tsx
packages/api/src/middlewares/integration.ts
packages/widgets/src/calendar/component.tsx
packages/widgets/src/calendar/index.ts
packages/widgets/src/definition.ts

feat: add support for calendar without integrations, add today mark

---

apps/nextjs/package.json
apps/nextjs/src/app/[locale]/manage/medias/_actions/copy-media.tsx
apps/nextjs/src/app/[locale]/manage/medias/page.tsx
packages/translation/src/lang/en.json
pnpm-lock.yaml

fix: copy only working for https and localhost, adding open in new tab

---

apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx

fix: url of batch link can get to long with 414 http code

---

apps/nextjs/src/app/[locale]/manage/tools/certificates/page.tsx

fix: certificate card delete button not reachable caused by overflow

---

apps/nextjs/src/env.ts
e2e/onboarding.spec.ts
packages/auth/env.ts
packages/common/env.ts
packages/db/env.ts

fix: empty env variables should be ignored

---

apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx

feat: add dropdown list for switching boards

---

apps/nextjs/src/components/board/items/item-content.tsx
packages/widgets/src/smart-home/entity-state/component.tsx
packages/widgets/src/smart-home/execute-automation/component.tsx

fix: entity state and execute automation cards aren't movable

---

packages/old-import/src/mappers/map-item.ts
packages/old-import/src/prepare/prepare-items.ts

fix: change error when section for item not found to logged warning and remove item

---

packages/api/src/router/widgets/rssFeed.ts
packages/cron-jobs/package.json
packages/cron-jobs/src/index.ts
packages/cron-jobs/src/jobs/rss-feeds.ts
packages/definitions/src/docs/homarr-docs-sitemap.ts
packages/request-handler/package.json
packages/request-handler/src/rss-feeds.ts
packages/widgets/package.json
packages/widgets/src/rssFeed/component.tsx
pnpm-lock.yaml

fix: add missing request handler for rss feeds

---

packages/integrations/src/download-client/nzbget/nzbget-integration.ts

fix: url-encode nzbget credentials

---

packages/translation/src/lang/en.json
packages/widgets/src/health-monitoring/component.tsx

fix: system health monitoring gets proxmox id passed

---

packages/translation/src/lang/en.json

Fixed typo in EN source language
<br/>
</div>

chore(lang): fix typo in english translation

---

apps/nextjs/src/app/[locale]/manage/apps/_form.tsx
packages/validation/src/app.ts

fix: app url not required

---

packages/widgets/src/_inputs/widget-multi-text-input.tsx

fix: multi-text-input not saving on blur

---

apps/websocket/src/main.ts

fix: websocket is not keep alive

---

packages/integrations/src/base/integration.ts

feat: log body integration test failure

---

apps/nextjs/src/app/[locale]/manage/apps/page.tsx

fix: app url line clamp

---

packages/api/src/router/integration/integration-router.ts

<br/>
</div>
See [2086](https://github.com/homarr-labs/homarr/issues/2086)

fix: automatic search engine creation

---

apps/nextjs/src/app/[locale]/boards/(content)/_creator.tsx
packages/common/src/string.ts

fix: board crashes with empty string favicon

---

apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx
apps/nextjs/src/app/api/trpc/[trpc]/route.ts
apps/nextjs/src/middleware.ts
packages/api/src/client.ts
packages/api/src/shared.ts

fix: use hostname for suspense query url

---

packages/widgets/src/health-monitoring/system-health.tsx

fix: negative curve radius system health

---

Dockerfile

fix(docker): missing production env variable

---

packages/ping/package.json
packages/ping/src/index.ts
pnpm-lock.yaml

fix: respect certificates for app ping

---

Dockerfile

ci: fix corepack issue

---

apps/nextjs/src/app/[locale]/manage/tools/api/components/api-keys.tsx
packages/api/src/router/apiKeys.ts
packages/translation/src/lang/en.json

feat: add api key delete

---

packages/integrations/src/interfaces/health-monitoring/healt-monitoring.ts
packages/integrations/src/openmediavault/openmediavault-integration.ts
packages/widgets/src/health-monitoring/system-health.tsx

fix: make system health temp optional

---

packages/api/src/router/search-engine/search-engine-router.ts
packages/db/migrations/mysql/0023_fix_on_delete_actions.sql
packages/db/migrations/mysql/meta/0023_snapshot.json
packages/db/migrations/mysql/meta/_journal.json
packages/db/migrations/sqlite/0023_fix_on_delete_actions.sql
packages/db/migrations/sqlite/meta/0023_snapshot.json
packages/db/migrations/sqlite/meta/_journal.json

fix: foreign key reference default search engine

---

packages/api/src/router/update-checker.ts

fix: add error handling for available updates

---

packages/common/src/stopwatch.ts
packages/cron-jobs-core/src/creator.ts
packages/cron-jobs-core/src/logger.ts
packages/cron-jobs/src/jobs/icons-updater.ts
packages/cron-jobs/src/lib/index.ts

feat: downgrade log level callback succeeded

---

.github/pull_request_template.md

fix: fix typo in pr template

---

packages/cli/src/commands/fix-usernames.ts
packages/cli/src/index.ts

feat(cli): add fix-username command to make all usernames lowercase

---

packages/integrations/test/pi-hole.spec.ts

test: pin pihole container for tests to v5 until v6 is implemented

---

apps/nextjs/src/app/[locale]/boards/_layout-creator.tsx

feat: redirect to login screen when no global home board

---

packages/widgets/src/app/app.module.css

fix(widgets): app icon not visible

---

.run/typecheck.run.xml
packages/integrations/src/interfaces/health-monitoring/healt-monitoring.ts
packages/integrations/src/openmediavault/openmediavault-types.ts
packages/widgets/src/health-monitoring/system-health.tsx

fix: omv invalid temperature when not available

---

packages/request-handler/src/update-checker.ts

fix: update checker logs incorrectly

---

apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx

fix(boards): add scrollarea to board-select

---

packages/api/src/router/widgets/media-requests.ts
packages/widgets/src/media-requests/list/component.tsx

fix(media-request): inconsistent sorting and reordering

---

packages/translation/src/lang/en.json
packages/widgets/src/media-requests/list/component.tsx

feat(media-request): show request status

---

packages/definitions/src/integration.ts
packages/integrations/src/base/creator.ts
packages/integrations/src/emby/emby-integration.ts
packages/integrations/src/jellyfin/jellyfin-integration.ts
packages/widgets/src/media-server/index.ts

feat(integration): add emby integration

---

apps/nextjs/src/app/[locale]/manage/apps/page.tsx
apps/nextjs/src/app/[locale]/manage/medias/page.tsx
apps/nextjs/src/app/[locale]/manage/search-engines/page.tsx

fix: affix hides pagination on mobile

---

packages/widgets/src/dns-hole/summary/component.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(dns-summary): improve responsive styles

---

packages/widgets/src/dns-hole/controls/component.tsx
packages/widgets/src/widgets-common.css

<br/>
</div>
**Before**
**After**
Part of #2531

fix(dns-controls): improve responsive styles

---

packages/widgets/src/app/component.tsx
packages/widgets/src/app/ping/ping-dot.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(app): improve responsive styles

---

packages/widgets/src/smart-home/entity-state/component.tsx
packages/widgets/src/smart-home/execute-automation/component.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(smart-home): improve responsive styles

---

packages/widgets/src/indexer-manager/component.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(indexer-manager): improve responsive styles

---

packages/widgets/src/media-requests/list/component.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(media-request-list): improve responsive styles

---

packages/translation/src/lang/en.json
packages/widgets/src/media-server/component.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(media-server): improve responsive styles

---

packages/api/src/router/widgets/calendar.ts
packages/cron-jobs/src/jobs/integrations/media-organizer.ts
packages/old-import/src/widgets/options.ts
packages/request-handler/src/calendar.ts
packages/translation/src/lang/en.json
packages/widgets/src/calendar/component.tsx
packages/widgets/src/calendar/index.ts

feat(calendar): add show-unmonitored option

---

packages/widgets/src/dns-hole/summary/component.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(dns-hole-summary): remove inconsistency for position of text

---

packages/widgets/src/calendar/calender-day.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(calendar): dropdown spans over whole screen

---

packages/widgets/src/notebook/component.tsx
packages/widgets/src/notebook/notebook.css
packages/widgets/src/notebook/notebook.tsx

<br/>
</div>
**Before**
**After**
Closes #2292

fix(notebook): css for checkboxes not working

---

packages/widgets/src/health-monitoring/cluster/cluster-health.tsx
packages/widgets/src/health-monitoring/cluster/resource-accordion-item.tsx
packages/widgets/src/health-monitoring/cluster/resource-table.tsx
packages/widgets/src/health-monitoring/component.tsx
packages/widgets/src/health-monitoring/rings/cpu-ring.tsx
packages/widgets/src/health-monitoring/rings/cpu-temp-ring.tsx
packages/widgets/src/health-monitoring/rings/memory-ring.tsx
packages/widgets/src/health-monitoring/system-health.tsx

<br/>
</div>
**Before**
**After**
Part of #2531

fix(system-health): improve responsive styles

---

apps/nextjs/src/app/[locale]/manage/integrations/page.tsx

fix: action icons not being rendered

---

packages/auth/permissions/board-permissions.ts

fix(permissions): unable to edit board with full board permissions

---

packages/validation/src/board.ts

fix: prohibit dot in board name

---

packages/cli/src/commands/fix-usernames.ts

<br/>
</div>
Posted in https://discord.com/channels/972958686051962910/1351978002548002867

fix(cli): fix-usernames command only fixes lowercase usernames

---

apps/nextjs/src/app/[locale]/init/_steps/user/init-user-form.tsx

<br/>
</div>
What the title says, avoids a double sign-in by calling `await signIn` after successfully creating the first user

feat: auto sign-in when creating the initial user

---

.vscode/i18n-ally-custom-framework.yml

chore(i18n): update regex patterns for i18n-ally

---

.run/All Tests.run.xml

feat: add jetbrains run profile

---

packages/widgets/src/_inputs/widget-app-input.tsx

feat: app dropdown add infinity scroll

---

development/package.json
pnpm-lock.yaml
pnpm-workspace.yaml
turbo.json

The aim of this PR is to make it easier to run the dev environment 
- Introduced a new development package with a Docker Compose script.
- Updated pnpm workspace to include the development directory.
- Changed Turbo UI setting from 'stream' to 'tui'.

chore: add development package and update workspace

---

packages/widgets/src/calendar/calender-day.tsx
packages/widgets/src/calendar/component.tsx

<br/>
</div>
**Before**:
**After**:

fix: calendar indicators

---

packages/old-import/src/import-error.ts
packages/old-import/src/import/collections/board-collection.ts
packages/old-import/src/import/test/board-collection.spec.ts
packages/old-import/src/move-widgets-and-apps-merge.ts

<br/>
</div>
Closes #2626
Tested it with multiple configs from myself and a special config only created for this use case. It all worked as expected

fix(import): autofix missing shapes for sidebars and some sections as well

---

packages/translation/src/config.ts
packages/translation/src/lang/en-gb.json
pnpm-lock.yaml

feat(lang): add english uk language

---

apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx

<br/>
</div>
https://discord.com/channels/972958686051962910/972958689155764326/1353033194420699328

fix(users): allow deletion of external users

---

.github/ISSUE_TEMPLATE/bug_report.yml

docs: add 1.13.0 to issue template

---

apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-dropdown.tsx
apps/nextjs/src/app/[locale]/manage/integrations/new/page.tsx

revert: ssg integration create

---

.github/ISSUE_TEMPLATE/bug_report.yml

docs: add 1.13.1 to issue template

---

packages/certificates/src/server.ts
packages/integrations/src/nextcloud/nextcloud.integration.ts

<br/>
</div>
✅ First has to be confirmed by OP that it works
Closes #2759

fix(nextcloud): issue with self signed certificates

---

nginx.conf
packages/validation/src/media.ts

fix(medias): upload size limited by nginx to 1mb

---

packages/api/src/router/widgets/notebook.ts
packages/widgets/src/notebook/notebook.tsx

fix(security): missing authorization check for changes to notebook widget

---

apps/nextjs/src/app/[locale]/boards/[name]/settings/_appereance.tsx
apps/nextjs/src/app/[locale]/boards/[name]/settings/_background.tsx
apps/nextjs/src/app/[locale]/boards/[name]/settings/_behavior.tsx
apps/nextjs/src/app/[locale]/boards/[name]/settings/_customCss.tsx
apps/nextjs/src/app/[locale]/boards/[name]/settings/_general.tsx
apps/nextjs/src/app/[locale]/boards/[name]/settings/_layout.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_change-home-board.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_change-search-preferences.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_first-day-of-week.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_ping-icons-enabled.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_profile-form.tsx
apps/nextjs/src/app/[locale]/manage/users/[userId]/security/_components/_change-password-form.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/_rename-group-form.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/members/_add-group-member.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/permissions/_group-permission-form.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/[id]/settings/_group-home-boards.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/_client.tsx
apps/nextjs/src/app/[locale]/manage/users/groups/_groups-table.tsx
apps/nextjs/src/app/[locale]/manage/users/invites/_components/invite-list.tsx
apps/nextjs/src/components/access/group-access-form.tsx
apps/nextjs/src/components/access/user-access-form.tsx
apps/nextjs/src/components/board/sections/category/category-edit-modal.tsx
apps/nextjs/src/components/board/sections/dynamic/dynamic-edit-modal.tsx
packages/modals-collection/src/boards/add-board-modal.tsx
packages/modals-collection/src/groups/add-group-modal.tsx
packages/modals-collection/src/invites/invite-create-modal.tsx
packages/widgets/src/health-monitoring/cluster/resource-popover.tsx
packages/widgets/src/modals/widget-advanced-options-modal.tsx
packages/widgets/src/modals/widget-edit-modal.tsx

<br/>
</div>
Simple code mod to search and replace in the codebase in order to to remove `color` prop when it is set to `teal` so that it uses the primary color instead (from the user preference)

feat: Prefer primary color

---

apps/nextjs/src/app/[locale]/manage/tools/certificates/page.tsx
packages/api/src/router/certificates/certificate-router.ts
packages/certificates/src/server.ts
packages/translation/src/lang/en.json
packages/validation/src/certificates.ts

<br/>
</div>
Closes #2644 
Closes #2809

fix(certificates): improve validation and prevent crash

---

apps/nextjs/src/app/[locale]/widgets/[kind]/_content.tsx
apps/nextjs/src/components/board/items/actions/create-item.ts
apps/nextjs/src/components/board/items/actions/test/duplicate-item.spec.ts
apps/nextjs/src/components/board/items/actions/test/mocks/item-mock.ts
apps/nextjs/src/components/board/items/item-content.module.css
apps/nextjs/src/components/board/items/item-content.tsx
packages/translation/src/lang/en.json
packages/validation/src/shared.ts
packages/widgets/src/modals/widget-advanced-options-modal.tsx

feat(widgets): add title to advanced options

---

.dockerignore
apps/tasks/package.json
apps/websocket/package.json
pnpm-lock.yaml

fix: cannot find module http-cookie-agent/http

---

packages/integrations/src/interfaces/media-requests/media-request.ts
packages/translation/src/lang/en.json
packages/widgets/src/media-requests/list/component.tsx

fix(media-request): add missing completed status

---

packages/auth/events.ts
packages/log/src/error.ts

* Helps with debugging
<br/>
</div>
Closes #3051

fix(logs): log error cause when object, sign in oidc debug messages

---

scripts/update-contributors.mjs

fix: updated contributors contain unnecessary data

---

packages/definitions/package.json
packages/definitions/src/docs/codegen.ts
pnpm-lock.yaml

<br/>
</div>
Confirmed by maintainer of community scripts that proxmox works again:
https://discord.com/channels/972958686051962910/973659470183956610/1372948185139515403
Closes #3108

fix(deps): missing dependencies in definitions package for docs link codegen

---

packages/auth/env.ts
packages/auth/providers/oidc/oidc-provider.ts

feat(auth): add account linking for oidc providers

---

apps/tasks/package.json
apps/websocket/package.json
packages/cli/package.json
packages/db/package.json
pnpm-lock.yaml

fix: esbuild not part of dependencies

---

apps/nextjs/src/styles/gridstack.scss

fix(items): resize handle overlaps header

---

packages/common/src/fetch-agent.ts
packages/common/src/test/fetch-agent.spec.ts
packages/cron-jobs-core/src/creator.ts

fix: reduce logging

---

packages/api/src/router/widgets/downloads.ts
packages/cron-jobs/src/jobs/integrations/downloads.ts
packages/integrations/src/download-client/aria2/aria2-integration.ts
packages/integrations/src/download-client/deluge/deluge-integration.ts
packages/integrations/src/download-client/nzbget/nzbget-integration.ts
packages/integrations/src/download-client/qbittorrent/qbittorrent-integration.ts
packages/integrations/src/download-client/sabnzbd/sabnzbd-integration.ts
packages/integrations/src/download-client/transmission/transmission-integration.ts
packages/integrations/src/interfaces/downloads/download-client-integration.ts
packages/integrations/test/aria2.spec.ts
packages/integrations/test/nzbget.spec.ts
packages/integrations/test/sabnzbd.spec.ts
packages/old-import/src/widgets/options.ts
packages/request-handler/src/downloads.ts
packages/translation/src/lang/en.json
packages/widgets/src/downloads/component.tsx
packages/widgets/src/downloads/index.ts
packages/widgets/src/options.ts
packages/widgets/src/rssFeed/component.tsx

<br/>
</div>
Closes #2504
Closes #2627

feat(downloads): add option to limit amount of items

---

packages/widgets/src/media-requests/stats/component.tsx

<br/>
</div>
Closes #2740
**Before**
**After**

fix(media-request-stats): users squeezed together

---

packages/modals-collection/src/apps/app-select-modal.tsx

fix(boards): app select modal images rendering issue

---

packages/api/src/router/search-engine/search-engine-router.ts

fix(search): removing server search engine causes loading error

---

apps/nextjs/next.config.ts

fix: csp prevents external stylesheets

---

apps/nextjs/next.config.ts

fix: module not found sshcrypto.node during development

---

packages/integrations/src/pi-hole/v6/pi-hole-integration-v6.ts

fix(pi-hole): cached session not invalidated when changing password

---

packages/widgets/src/widget-integration-select.tsx

fix(widget-integration-select): fixing `<p>` being descendant of `<p>`

---

packages/integrations/src/interfaces/media-requests/media-request.ts
packages/translation/src/lang/en.json
packages/widgets/src/media-requests/list/component.tsx

fix(jellyseerr): add missing deleted media status

---

.env.example
packages/certificates/src/server.ts

fix: unable to change certificate path for running from source

---

packages/widgets/src/calendar/calendar-event-list.tsx

fix: #3678 season number badge calendar

---

packages/definitions/src/integration.ts
packages/integrations/src/base/creator.ts
packages/integrations/src/github-container-registry/github-container-registry-integration.ts

refactor: renamed `GitHubPackages` integration to `GitHubContainerRegistry`

---

packages/api/src/root.ts
packages/api/src/router/info.ts

feat(api): add info endpoint

---

apps/nextjs/src/app/[locale]/manage/_components/hero-banner.tsx

fix: not hardcode hero banner scroll

---

apps/nextjs/src/app/[locale]/manage/apps/page.tsx
packages/forms-collection/src/new-app/_form.tsx
packages/widgets/src/app/component.tsx

feat(app-widget): multiline description

---

apps/nextjs/src/app/[locale]/manage/apps/page.tsx
packages/forms-collection/src/new-app/_form.tsx
packages/old-import/src/mappers/map-item.ts
packages/translation/src/lang/en.json
packages/widgets/src/_inputs/widget-select-input.tsx
packages/widgets/src/app/component.tsx
packages/widgets/src/app/index.ts

<br/>
</div>
Closes #3026
Closes #3506 
First merge #3873

feat(app-widget): add layout option

---

package.json
pnpm-lock.yaml

<br/>
</div>
Fixes most issues of https://github.com/homarr-labs/homarr/security/dependabot
It was done with `pnpm audit --fix`, manually changing all overlapping ranges to the top one and finally install the deps with `pnpm install`

fix(security): deepsource issues

---

packages/old-import/src/widgets/definitions/rss.ts
packages/old-import/src/widgets/options.ts
packages/translation/src/lang/en.json
packages/widgets/src/rssFeed/component.tsx
packages/widgets/src/rssFeed/index.ts

feat(rss-widget): add hide description option

---

.github/workflows/skip-renovate-stability-days.yml

ci: add job to skip renovate stability days for non renovate prs

---

packages/common/env.ts
packages/common/src/dns.ts

<br/>
</div>
Some users experience dns issues after the latest update (v1.36.0)

fix(dns): disable caching by default

---

.github/ISSUE_TEMPLATE/bug_report.yml
packages/common/env.ts
packages/common/src/dns.ts

chore(release): hotfix for dns-caching

---

packages/old-import/src/widgets/options.ts
packages/widgets/src/iframe/component.tsx
packages/widgets/src/iframe/index.ts

<br/>
</div>
Closes #3783
Docs in https://github.com/homarr-labs/documentation/pull/398
This pr also removes the `allowTransparency` option as it does not do anything in modern browsers and transparency is always enabled.

fix(iframe): disable scrolling not working

---

packages/integrations/src/plex/plex-integration.ts

fix(plex-integration): unknown badge shown for added tv-shows

---

packages/translation/src/lang/en.json
packages/widgets/src/notebook/notebook.tsx

feat(notebook-widget): add confirmation on dismiss

---

.github/workflows/automatic-approval.yml
.github/workflows/crowdin-schedule-download.yml
.github/workflows/deployment-docker-image.yml
.github/workflows/deployment-weekly-release.yml
.github/workflows/on-release.yml
.github/workflows/update-contributors.yml
.github/workflows/update-integration-list.yml

refactor(ci): migrate tibdex/github-app-token to actions/create-github-app-token

---

apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/tasks-table.tsx

feat(tasks): add one second interval

---

.github/workflows/on-release.yml

ci(on-release): update bug report template failing

---

packages/translation/src/lang/en.json
packages/widgets/src/system-resources/chart/combined-network-traffic.tsx
packages/widgets/src/system-resources/chart/common-chart.tsx
packages/widgets/src/system-resources/chart/cpu-chart.tsx
packages/widgets/src/system-resources/chart/memory-chart.tsx
packages/widgets/src/system-resources/chart/network-traffic.tsx
packages/widgets/src/system-resources/component.tsx
packages/widgets/src/system-resources/index.ts

feat(system-resources-widget): add label display mode option

---

packages/api/src/router/widgets/calendar.ts
packages/widgets/src/calendar/component.tsx

feat(calendar): add periodic live updates

---

packages/integrations/src/emby/emby-integration.ts
packages/integrations/src/interfaces/media-server/media-server-types.ts
packages/integrations/src/jellyfin/jellyfin-integration.ts
packages/integrations/src/mock/data/media-server.ts
packages/integrations/src/plex/plex-integration.ts
packages/translation/src/lang/en.json
packages/widgets/src/media-server/component.tsx

<br/>
</div>
In oldmarr:
Now:
Closes #2401

feat(media-server): add stats for nerds
