- apps/nextjs/src/components/board/sections/content.tsx
- apps/nextjs/src/components/board/sections/gridstack/init-gridstack.ts
- packages/widgets/src/app/component.tsx
by defining margin depending on screen size, removing general padding on card of items and reducing size of no app icon
<br/>
</div>
> style: improve styling of items on board

- packages/db/driver.ts
<br/>
</div>
As it can be seen above typescript spends a lot of type comparing the two types of databases. That's the reason I used the `as unknown as never` conversation so it hsa not to do that
> perf: improve typescript performance

- packages/api/src/trpc.ts
It now includes the username of the person doing the tRPC request (because the user id is not enough)
> chore: Update trpc logger info

- apps/nextjs/src/app/[locale]/boards/(content)/_context.tsx
- apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
- apps/nextjs/src/components/board/editMode.ts
- apps/nextjs/src/components/board/sections/category/category-menu.tsx
- apps/nextjs/src/components/board/sections/content.tsx
- apps/nextjs/src/components/board/sections/empty-section.tsx
- apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts
> refactor: make disabling / enabling of edit mode part of board context so it's not stored over multiple boards

- .vscode/settings.json
- README.md
- apps/nextjs/package.json
- apps/nextjs/src/app/[locale]/layout.tsx
- apps/nextjs/src/app/[locale]/manage/settings/_components/analytics.settings.tsx
- apps/nextjs/src/components/layout/analytics.tsx
- apps/tasks/package.json
- apps/tasks/src/jobs.ts
- apps/tasks/src/jobs/analytics.ts
- packages/analytics/index.ts
- packages/analytics/package.json
- packages/analytics/src/constants.ts
- packages/analytics/src/index.ts
- packages/analytics/src/send-server-analytics.ts
- packages/analytics/tsconfig.json
- packages/api/src/router/serverSettings.ts
- pnpm-lock.yaml
> feat: add analytics

- .github/workflows/renovate-automatic-approval
<br/>
</div>
This allows us to use auto merge while we require a approval at least.
> ci: add github action that approves pull requests from renovate automatically

- packages/translation/src/lang/en.ts
- packages/widgets/src/app/component.tsx
- packages/widgets/src/app/index.ts
<br/>
</div>
CSS for putting the text in a row (just to show how easy it is)
```CSS
.app-row-elements { .app-flex-wrapper {
flex-direction: row !important;
}}
```
> feat: App tile scalability

- package.json
- packages/integrations/test/pi-hole.spec.ts
- packages/integrations/tsconfig.json
- pnpm-lock.yaml
> test: add pi-hole test container integration test

- apps/tasks/package.json
- apps/tasks/src/main.ts
- apps/tasks/src/undici-log-agent-override.ts
- pnpm-lock.yaml
<br/>
</div>
All credit goes to Meier- I only adjusted the format & logging
> feat: add undici fetch interceptor

- packages/api/src/router/cron-jobs.ts
- packages/api/src/router/log.ts
- packages/api/src/router/user.ts
- packages/api/src/router/widgets/app.ts
- packages/api/src/router/widgets/media-server.ts
- packages/api/src/router/widgets/smart-home.ts
<br/>
</div>
```
@homarr/websocket:dev: node:internal/webstreams/readablestream:1069
@homarr/websocket:dev:       throw new ERR_INVALID_STATE.TypeError('Controller is already closed');
@homarr/websocket:dev:       ^
@homarr/websocket:dev:
@homarr/websocket:dev: TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
@homarr/websocket:dev:     at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1069:13)
@homarr/websocket:dev:     at Object.next (homarr/node_modules/@trpc/server/dist/observable/observable.mjs:117:32)
@homarr/websocket:dev:     at Object.next …
```
> fix: controller is already closed trpc subscription observable error

- apps/nextjs/src/app/[locale]/manage/_components/hero-banner.module.css
fix the animation loop hitch in the banner of the management page.
Don't ask me why 50.8%, I just starred at my screen very long until the value caused the hitch to disappear.
> fix: Manage banner animation hitch fix

- .github/workflows/renovate-automatic-approval.yml
<br/>
</div>
This will no longer spam us when one pull request can not be merged and then other pull requests open / synchronize
> fix: renovate approval run for all pull requests on every pull request change

- .github/workflows/renovate-automatic-approval.yml
<br/>
</div>
The issue lied in my understanding of the branches restriction. I meant that it would restrict the head branches but it actually restricts based on the base branches. Additionally I replaced the actor name with an id so now it is impossible to fake it as only the github app has this id
> fix: renovate approval workflow not running

- apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
- apps/nextjs/src/components/user-avatar-menu.tsx
- packages/widgets/src/notebook/notebook.tsx
<br/>
</div>
This adds the following hotkeys:
- `mod + e` to toggle edit mode
- `mod + j` to toggle color scheme
- `mod + s` (only inside the notebook widget) save the notebook
> feat: add hotkeys

- packages/cron-jobs/src/jobs/ping.ts
<br/>
</div>
This fixes that it waits for each timeout of those fetches which can result in times higher than the ping cycle of one minute. All pings should be done after less than 15 seconds.
> fix: improve ping performance

- packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
> fix: sonarr testConnectionAsync url

- packages/integrations/src/adguard-home/adguard-home-integration.ts
- packages/widgets/src/dns-hole/controls/TimerModal.tsx
- packages/widgets/src/dns-hole/controls/component.tsx
> fix: DnsHole controls timer

- apps/nextjs/src/app/[locale]/_client-providers/trpc.tsx
- apps/nextjs/src/app/[locale]/manage/tools/logs/client.tsx
- apps/nextjs/src/app/[locale]/manage/tools/logs/page.tsx
- apps/nextjs/src/app/[locale]/manage/tools/logs/terminal.tsx
> fix: websocket url is always localhost

- packages/cron-jobs/src/jobs/integrations/media-organizer.ts
- packages/integrations/src/base/creator.ts
- packages/integrations/src/index.ts
- packages/integrations/src/media-organizer/radarr/radarr-integration.ts
> feat: radarr integration

- packages/widgets/src/iframe/component.tsx
<br/>
</div>
Now the iframe can be moved in edit mode as the user wants, the content can not be interacted with during edit mode.
Closes #1075
> fix: hard to move iframe widget #1075

- .github/workflows/deployment-docker-image.yml
<br/>
</div>
Caching pnpm dependencies is harder because we install & build within the docker builder.
See https://github.com/actions/setup-node/issues/801#issuecomment-1772094807 and https://dev.to/henryjw/caching-pnpm-modules-in-docker-builds-in-github-actions-mj7 for further information. The benefit with caching dependencies likely won't be huge -> therefore I suggest disabling caching here until we run into performance problems with the actions - then we can act again.
> fix: node cache cleanup error

- packages/icons/src/icons-fetcher.ts
- packages/icons/src/repositories/github.icon-repository.ts
- packages/icons/src/repositories/icon-repository.ts
- packages/icons/src/repositories/jsdelivr.icon-repository.ts
- packages/icons/src/types/icon-repository-license.ts
Closes #1105
Add Simple-Icons:
> Monochrome Icons.
> Can change color by adding "/{colour}" at the end of the link, can also be in hex format.
Add Selfh.st icons:
> Self-hosting focused collection.
> Completes current collections with icons that are not available from other sources.
Refactor:
> Change regex function (Wrongly named too btw) with path parse.
> Add blob replace: "{1}" -> icon name only and not whole path.
> Improve file extension checker
This pushes us over the 10k icons
> feat: Add Simple-Icons and Selfh.st collections

- packages/integrations/package.json
- packages/integrations/src/download-client/nzbget/nzbget-integration.ts
- packages/integrations/src/download-client/nzbget/nzbget-types.ts
- packages/integrations/test/nzbget.spec.ts
- packages/widgets/src/downloads/component.tsx
- pnpm-lock.yaml
Fetch method POST achieves basically the same as typed-rpc.
Could actually use all that was already made and just swap it.
Allows to remove a dependency.
Closes #1104 
To delete once merged
> refactor: Remove typed-rpc dependency and used fetch instead

- packages/widgets/src/indexer-manager/component.tsx
Make indexer manager scaling behave like the other widget.
Fixed improper base flex behaviour.
Added class naming to all components.
> fix: indexer manager UI behaviour + class naming

- packages/cron-jobs/src/jobs/icons-updater.ts
> fix: insert limit of sqlite is smaller than amount of icons

- .github/workflows/deployment-docker-image.yml
The conditional statements were all in the form of `input || true`, presumably in an effort to treat this as `true` if the input was not set as it would be when the trigger is a push rather than a manual dispatch (`null || true` => `true`). However `false || true` also results in `true`, so this would just always result in `true`.
Changing this to `!= false` does result in the desired behaviour:
- Enabled: `true != false` => `true`
- Disabled: `false != false` => `false`
- Unset: `null != false` => `true`
---
It was always looking at the `dev` branch for the commit messages in the versioning step, which meant that running it against a different branch would not have the desired result.
> fix: various issues with docker image workflow

- Dockerfile
The container image always used an amd64 image as base, both for the build steps as well as for the runtime. For the runner this resulted in the containers just not booting with the error `exec /usr/local/bin/docker-entrypoint.sh: exec format error`.
I first tried fixing this by adjusting this only for the runner, but this resulted in a segfault later on, presumably due to some binary component in the build/dependencies that was now build for the wrong architecture, so I just ended up switching the entire thing over to use the target architecture.
Fixes #1125.
> fix: container image always being on AMD64 arch

- apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
- apps/nextjs/src/app/[locale]/layout.tsx
- packages/auth/callbacks.ts
- packages/auth/configuration.ts
- packages/auth/test/callbacks.spec.ts
- packages/common/src/cookie.ts
<br/>
</div>
This fixes the bug that sometimes the whole screen is black and there are no colors. The reason was, that we only used the color scheme when signed in and otherwise it was not set. Now I use a cookie and when you log in it's set to that one saved for the specific user
> fix: issue with color scheme in layout

- packages/modals/src/confirm-modal.tsx
<br/>
</div>
Resolves https://discord.com/channels/972958686051962910/1267085405631807548
> fix: confirm not selected by default in confirm modal

- apps/nextjs/src/app/[locale]/manage/tools/api/components/api-keys.tsx
- apps/nextjs/src/app/[locale]/manage/tools/api/components/copy-api-key-modal.tsx
- apps/nextjs/src/app/[locale]/manage/tools/api/components/swagger-ui.tsx
- apps/nextjs/src/app/[locale]/manage/tools/api/page.tsx
- apps/nextjs/src/app/[locale]/manage/tools/api/swagger-ui.css
- apps/nextjs/src/app/api/[...trpc]/route.ts
- packages/api/src/open-api.ts
- packages/api/src/root.ts
- packages/api/src/router/apiKeys.ts
- packages/api/src/router/app.ts
- packages/api/src/router/user.ts
- packages/auth/callbacks.ts
- packages/auth/server.ts
- packages/db/migrations/mysql/0009_wakeful_tenebrous.sql
- packages/db/migrations/mysql/meta/0009_snapshot.json
- packages/db/migrations/mysql/meta/_journal.json
- packages/db/migrations/sqlite/0009_stale_roulette.sql
- packages/db/migrations/sqlite/meta/0009_snapshot.json
- packages/db/migrations/sqlite/meta/_journal.json
- packages/db/schema/mysql.ts
- packages/db/schema/sqlite.ts
- packages/translation/src/lang/en.ts
> feat: add api keys

- apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
> feat: populate integration name for new integrations automatically

- apps/nextjs/src/app/[locale]/_client-providers/mantine.tsx
- apps/nextjs/src/app/[locale]/layout.tsx
- packages/auth/callbacks.ts
- packages/db/schema/mysql.ts
- packages/db/schema/sqlite.ts
- packages/definitions/src/user.ts
<br/>
</div>
Closes https://discord.com/channels/972958686051962910/1295792744601616414
> fix: prevent flickering by removing auto color scheme and default background color

- packages/api/src/router/widgets/health-monitoring.ts
- packages/widgets/src/health-monitoring/component.tsx
> fix: sort & last seen

- apps/nextjs/src/middleware.ts
> fix: middleware fetch failed for docker container

- .github/workflows/deployment-docker-image.yml
- tooling/github/setup/action.yml
<br/>
</div>
> Node is never needed for docker deployment
> fix: change node-version for composite setup action to 22, remove unnecessary installation of node from docker deployment

- apps/nextjs/src/app/[locale]/manage/users/groups/[id]/_reserved-group-alert.tsx
- packages/translation/src/lang/en.json
> fix: everyone group page throws error

- packages/cron-jobs-core/src/creator.ts
- packages/cron-jobs-core/src/expressions.ts
- packages/cron-jobs-core/src/group.ts
- packages/cron-jobs/package.json
- packages/cron-jobs/src/index.ts
- packages/cron-jobs/src/jobs/session-cleanup.ts
- packages/translation/src/lang/en.json
- pnpm-lock.yaml
> fix: sessions from inactive providers can still be used

- .vscode/extensions.json
- .vscode/i18n-ally-custom-framework.yml
- .vscode/settings.json
| Before 😭 | After 😎 |
|--------|--------|
| <img width="739" alt="image" src="https://github.com/user-attachments/assets/7981de9d-d67a-424a-aecf-d08e4fed7d65"> | <img width="835" alt="image" src="https://github.com/user-attachments/assets/72bbbfe9-83de-4039-ae09-fdb1da721b21">  | 
> fix: fix i18n-ally extension config

- apps/tasks/src/test/undici-log-agent-override.spec.ts
- apps/tasks/src/undici-log-agent-override.ts
> fix: dispatch request-logger hides negative numbers, dates and date times

- packages/translation/src/middleware.ts
> fix: matcher for translation middleware only supports en and de

- apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
- apps/nextjs/src/components/user-avatar-menu.tsx
- packages/translation/src/lang/en.json
> fix: add beforeunload logic for board in edit mode

- apps/nextjs/src/components/icons/picker/icon-picker.tsx
<br/>
</div>
Previously the whole page showed a loading spinner and most of the times you were not able to enter even one character. Now it just works. Also added a debounce to not spam the server to much.
> fix: icon picker suspense issue

- .gitattributes
This fixes an issue on linux where the line endings would result in the following changes:
> fix: fix binary conflicts for linux

- Dockerfile
<br/>
</div>
We misused the prune functionality from turborepo which allows to only include the necessary things for installation and build. But as we need everything in the same image, we can simply skip this mess and build normally with all files present and then copy the build files to the run step.
This also resolves the issue with docker build in #1586 which occured because the patched dependency was no longer part of the package.json after prune.
I tested the image in this state locally, size is about 330 MB and it works as expected
> fix: remove unnecessary complex copy and build steps in dockerfile

- apps/nextjs/src/app/[locale]/manage/tools/docker/error.tsx
- packages/api/src/router/docker/docker-router.ts
- packages/translation/src/lang/en.json
- packages/widgets/src/errors/base-component.tsx
> feat: add error page for docker tools page

- Dockerfile
- development/docker-run.cmd
- e2e/shared/create-homarr-container.ts
- packages/auth/configuration.ts
- scripts/generateEncryptionKey.js
- scripts/generateRandomSecureKey.js
- scripts/run.sh
<br/>
</div>
Previously `AUTH_SECRET` was a required env variable during the early adopters program
> ci: generate auth secret in production

- apps/nextjs/src/components/layout/header/user.tsx
> fix: permission required for home page

- packages/integrations/src/base/integration.ts
- packages/integrations/src/jellyfin/jellyfin-integration.ts
> fix: jellyfin integration does not allow username password auth

- packages/api/src/router/integration/integration-router.ts
- packages/definitions/src/integration.ts
While adding the encodeURI function to the query (Spaces were not working) I noticed the implementation was not using the category system, after discussing it with Mani it was asserted that it was only for personal preference/meta reasons.
I am suggesting this PR as a change to keep the system centralized using the generalized category system instead.
(This also implements the encodeURI fix, which I can make a new PR for if this one doesn't get accepted).
> refactor: Move integration search flag to categories

- .github/workflows/deployment-docker-image.yml
- apps/nextjs/src/app/[locale]/init/_steps/import/import-dropzone.tsx
<br/>
</div>
Some users were unable to import the zip archive as we only supported default `application/zip` but not compressed variant
> fix: allow additional file-type for oldmarr import

- apps/nextjs/src/components/board/sections/content.tsx
<br/>
</div>
Closes #1102 
The bug happens because the order in the virtual DOM (React) and in the real dom (Modified by Gridstack) do not match. The reason for this is that Gridstack creates the items itself and places them in the correct x / y order into the gridstack section. While we did not respect the correct order during the rendering of the virtual DOM it resulted in a mixed up order which then was rendered in the wrong order because suspense only had a reference to the elements at the specific places
> fix(board): tiles order not respected on firefox

- .github/workflows/deployment-docker-image.yml
> ci(docker): always push image

- packages/api/src/router/widgets/index.ts
- packages/api/src/router/widgets/minecraft.ts
- packages/cron-jobs/src/index.ts
- packages/cron-jobs/src/jobs/minecraft-server-status.ts
- packages/definitions/src/widget.ts
- packages/redis/src/index.ts
- packages/redis/src/lib/channel.ts
- packages/request-handler/src/lib/cached-widget-request-handler.ts
- packages/request-handler/src/minecraft-server-status.ts
- packages/translation/src/lang/en.json
- packages/widgets/src/index.tsx
- packages/widgets/src/minecraft/server-status/component.tsx
- packages/widgets/src/minecraft/server-status/index.ts
<br/>
</div>
Using the following api: https://api.mcsrvstat.us/
> feat(widget): add minecraft server status widget

- packages/integrations/src/prowlarr/prowlarr-integration.ts
- packages/integrations/src/prowlarr/prowlarr-types.ts
> fix: prowlarr integration indexers status changed from id to indexerId

- apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
- packages/api/src/router/app.ts
- packages/icons/src/auto-icon-searcher.ts
- packages/modals-collection/src/docker/add-docker-app-to-homarr.tsx
- packages/modals-collection/src/docker/index.ts
- packages/modals-collection/src/index.ts
- packages/translation/src/lang/en.json
- packages/validation/src/app.ts
> feat: docker add to homarr

- packages/translation/src/lang/en.json
> fix(translation): query parameter in search with escaped

- packages/translation/src/lang/en.json
- packages/validation/src/app.ts
- packages/validation/src/integration.ts
- packages/validation/src/search-engine.ts
- packages/widgets/src/iframe/component.tsx
> fix(security): restrict link protocols to http and https

- apps/nextjs/src/components/board/items/item-select-modal.tsx
- packages/translation/src/lang/en.json
> feat(items): add search to selection

- apps/nextjs/src/components/board/items/item-content.tsx
> fix(widget): set-options from widget components should be partial

- package.json
- packages/integrations/test/nzbget.spec.ts
<br/>
</div>
Reason: It always fails since the latest nzbget release and scan is no longer reliable (append is anyway the better solution)
> test: adjust nzbget test to use append instead of scan

- packages/old-import/src/mappers/map-integration.ts
> fix: add missing old-import proxmox integration kind mapping

- apps/nextjs/src/app/[locale]/manage/users/[userId]/general/_components/_ping-icons-enabled.tsx
Switch needs "checked" to be set instead of value.
Maybe could have changed the form to set a different field instead.
closes #1998
> fix: User options switch on load value always false

- packages/widgets/src/health-monitoring/system-health.tsx
> fix: health monitoring cpu temp ring when no data, disks health when no data

- apps/nextjs/src/components/board/items/actions/create-item.ts
- apps/nextjs/src/components/board/items/actions/duplicate-item.ts
- apps/nextjs/src/components/board/items/actions/empty-position.ts
- apps/nextjs/src/components/board/items/actions/test/create-item.spec.ts
- apps/nextjs/src/components/board/items/actions/test/duplicate-item.spec.ts
- apps/nextjs/src/components/board/items/actions/test/empty-position.spec.ts
- apps/nextjs/src/components/board/items/actions/test/shared.ts
- apps/nextjs/src/components/board/items/item-actions.tsx
> fix: add item does not respect dynamic sections

- apps/nextjs/src/app/[locale]/manage/users/[userId]/general/page.tsx
> fix: hide current language switch in other users preferences

- packages/widgets/src/clock/component.tsx
> fix: date & time widget padding cut off

- apps/nextjs/src/components/board/sections/category-section.tsx
> feat: add opacity for categories

- apps/nextjs/src/components/board/sections/category/category-menu-actions.tsx
- apps/nextjs/src/components/board/sections/category/category-menu.tsx
- apps/nextjs/src/components/board/sections/category/filter.ts
- packages/translation/src/lang/en.json
> feat: open all apps in category

- packages/db/driver.ts
<br/>
</div>
Closes #2021
When running the current version on dev and stopping the local mysql container, the app crashes (see logf from before). If I changed the code to pool with keep alive, it showed errors during the downtime and then it just continued as if nothing happened.
Before:
```
@homarr/nextjs:dev:  ✓ Compiled /[locale]/manage/users/[userId]/general in 10.4s
@homarr/nextjs:dev: (node:22980) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
@homarr/nextjs:dev: (Use `node --trace-deprecation ...` to show where the warning was created)
@homarr/tasks:dev: …
```
> fix: add mysql pool with keep-alive to not close the connection

- packages/integrations/src/media-organizer/lidarr/lidarr-integration.ts
- packages/integrations/src/media-organizer/media-organizer-integration.ts
- packages/integrations/src/media-organizer/radarr/radarr-integration.ts
- packages/integrations/src/media-organizer/readarr/readarr-integration.ts
- packages/integrations/src/media-organizer/sonarr/sonarr-integration.ts
> fix: missing cover types media organizers

- apps/nextjs/src/app/[locale]/boards/[name]/settings/_appereance.tsx
- apps/nextjs/src/app/[locale]/boards/[name]/settings/page.tsx
- apps/nextjs/src/components/board/items/item-content.tsx
- apps/nextjs/src/components/board/sections/category-section.tsx
- apps/nextjs/src/components/board/sections/dynamic-section.tsx
- packages/api/src/router/board.ts
- packages/db/migrations/mysql/0026_add-border-radius.sql
- packages/db/migrations/mysql/meta/0026_snapshot.json
- packages/db/migrations/mysql/meta/_journal.json
- packages/db/migrations/sqlite/0026_add-border-radius.sql
- packages/db/migrations/sqlite/meta/0026_snapshot.json
- packages/db/migrations/sqlite/meta/_journal.json
- packages/db/package.json
- packages/db/schema/mysql.ts
- packages/db/schema/sqlite.ts
- packages/translation/src/lang/en.json
- packages/validation/src/board.ts
- pnpm-lock.yaml
> feat: add tile border radius

- apps/nextjs/src/app/[locale]/manage/medias/page.tsx
<br/>
</div>
Closes #2253
**Before:**
**After:**
> fix(medias): svg files don't load in list

- .github/workflows/deployment-docker-image.yml
<br/>
</div>
This pull request fixes the issue that we had in the last releases where the current state of the main branch with the updated package.json version were not rebased onto dev. Also a later rebase with force push resulted in many random commits showing in prs of that time
> ci: fix rebase for dev not working on release

- packages/api/src/router/app.ts
- packages/api/src/router/test/app.spec.ts
- packages/db/migrations/mysql/0028_add_app_ping_url.sql
- packages/db/migrations/mysql/meta/0028_snapshot.json
- packages/db/migrations/mysql/meta/_journal.json
- packages/db/migrations/sqlite/0028_add_app_ping_url.sql
- packages/db/migrations/sqlite/meta/0028_snapshot.json
- packages/db/migrations/sqlite/meta/_journal.json
- packages/db/schema/mysql.ts
- packages/db/schema/sqlite.ts
- packages/forms-collection/src/new-app/_form.tsx
- packages/modals-collection/src/docker/add-docker-app-to-homarr.tsx
- packages/old-import/src/import-apps.ts
- packages/old-import/src/mappers/map-app.ts
- packages/translation/src/lang/en.json
- packages/validation/src/app.ts
- packages/widgets/src/app/component.tsx
- packages/widgets/src/bookmarks/add-button.tsx
> feat: add app ping url

- apps/nextjs/src/app/[locale]/boards/(content)/_creator.tsx
<br/>
</div>
Fixes the following issue:
```
@homarr/nextjs:dev: Error: Route "/[locale]/boards/[name]" used `params.name`. `params` should be awaited before using its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
@homarr/nextjs:dev:     at getInitialBoardAsync (file://C%3A/Dev/alparr-labs/homarr/apps/nextjs/apps/nextjs/src/app/%5Blocale%5D/boards/%28content%29/%5Bname%5D/%28board%29/_definition.tsx:6:31)
@homarr/nextjs:dev:     at Module.generateMetadataAsync (file://C%3A/Dev/alparr-labs/homarr/apps/nextjs/apps/nextjs/src/app/%5Blocale%5D/boards/%28content%29/_creator.tsx:46:28)
@homarr/nextjs:dev:   4 | …
```
> fix: await params for board metadata

- .github/renovate.json5
- apps/nextjs/package.json
- packages/api/package.json
- packages/auth/package.json
- packages/common/package.json
- packages/modals-collection/package.json
- packages/old-import/package.json
- packages/settings/package.json
- packages/spotlight/package.json
- packages/translation/package.json
- packages/ui/package.json
- packages/widgets/package.json
- pnpm-lock.yaml
- tooling/eslint/package.json
<br/>
</div>
```
@homarr/nextjs:dev: FATAL: An unexpected Turbopack error occurred. Please report the content of C:\Users\meier\AppData\Local\Temp\next-panic-e6f85ab21a1d12a33792ad7bda6c35f4.log, along with a description of what you were doing when the error occurred, to https://github.com/vercel/next.js/issues/new?template=1.bug_report.yml
```
- Disabled nextjs updated for now
- Reenabled dockerode updates as it was resolved more than a month ago
> fix(deps): downgrade to next 15.1.7 cause of turbopack crash with 15.2.0 and above

- packages/api/src/router/board.ts
<br/>
</div>
Closes #2218
Tried it out with board named `GuGuS` and was able to open it with `/boards/gugus`:
> fix(boards): case-sensitive board names in url

- packages/old-import/src/mappers/map-board.ts
<br/>
</div>
Closes #2246
From
To
> fix(old-import): default logo and favicon not replaced

- packages/cron-jobs-core/src/creator.ts
<br/>
</div>
Some axios errors have a length of more than 1500 lines
Closes #2204
> fix(logs): add special case for axios error to prevent huge error messages

- packages/analytics/src/send-server-analytics.ts
- packages/api/src/router/group.ts
- packages/api/src/router/home.ts
- packages/api/src/router/icons.ts
- packages/api/src/router/search-engine/search-engine-router.ts
> refactor: replace drizzle count with $count

- development/docker-run.cmd
- scripts/entrypoint.sh
- scripts/run.sh
> feat: add sigterm support

- apps/nextjs/src/app/[locale]/manage/tools/docker/docker-table.tsx
- packages/modals-collection/src/docker/add-docker-app-to-homarr.tsx
> fix: docker add to homarr layout overflow

- packages/integrations/src/pi-hole/pi-hole-integration-factory.ts
> fix(pi-hole): wrong fetch used in factory

- packages/old-import/src/import/collections/board-collection.ts
- packages/old-import/src/mappers/map-column-count.ts
- packages/old-import/src/move-widgets-and-apps-merge.ts
- packages/old-import/src/prepare/prepare-items.ts
- packages/old-schema/src/index.ts
- packages/old-schema/src/tile.ts
> fix(import): autofix missing sizes of items with grid-algorithm

- packages/old-import/src/widgets/options.ts
- packages/translation/src/lang/en.json
- packages/widgets/src/bookmarks/component.tsx
- packages/widgets/src/bookmarks/index.tsx
<br/>
</div>
**Before**
**After**
**New options**
**Difference between `grid` (right) and `gridHorizontal` (left)**
Part of #2531
> fix(bookmarks): improve responsive styles

- packages/widgets/src/clock/component.tsx
<br/>
</div>
**Before**
**After**
Part of #2531
> fix(date-time): improve responsive styles

- packages/request-handler/src/minecraft-server-status.ts
- packages/widgets/src/minecraft/server-status/component.tsx
<br/>
</div>
Closes https://www.reddit.com/r/homarr/comments/1j6ujgg/minecraft_bedrock_error/?rdt=58902
> fix(minecraft-status): wrong api path for bedrock

- packages/log/src/index.ts
<br/>
</div>
Logs now look like the following when the logged value is an error:
This means in general all error logs should be logged as error like:
`logger.error(new Error(`Failed to parse something`, { cause: catchedError }))`
This way it will show the stack trace with the current log statements location and all the below errors
> feat(logs): improve error logs with stacked causes

- apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-form.tsx
- packages/translation/src/lang/en.json
> feat(integrations): add checkbox to add app

- apps/nextjs/src/app/[locale]/manage/integrations/new/[id]/page.tsx
- apps/nextjs/src/app/[locale]/manage/integrations/new/_integration-new-dropdown.tsx
Reworked the `/integration/new?kind={ID}` to `/integration/new/{ID}` so that the pages can be created at build-time, making them prerendered as static HTML (because it uses generateStaticParams)
> feat: SSG integration creation page

- packages/db/migrations/seed.ts
- packages/db/queries/server-setting.ts
- packages/definitions/src/docs/index.ts
- packages/definitions/src/test/docs.spec.ts
<br/>
</div>
Added the following search engines as default during the seeding process. Feel free to directly edit the code if you'd want to use another one than Google / add more search engines. 
I also set Homarr docs as the default search engine
> feat: add default search engines seeding / set homarr docs as global server search engine

- apps/nextjs/src/app/api/[...trpc]/route.ts
- apps/nextjs/src/app/api/trpc/[trpc]/route.ts
- packages/api/src/router/integration/integration-test-connection.ts
- packages/api/src/router/update-checker.ts
- packages/auth/configuration.ts
- packages/log/src/error.ts
- packages/log/src/index.ts
- packages/log/src/metadata.ts
- packages/ping/src/index.ts
- packages/request-handler/src/lib/cached-request-integration-job-handler.ts
<br/>
</div>
This is how it looks like for a failed integration job:
```
2025-03-26T19:59:15.799Z error: Failed to run integration job integration=c9twazvm8d6zbnkgy78792f5 inputHash='W3t9XQ=='
at <anonymous> (C:\Dev\alparr-labs\homarr\packages\request-handler\src\lib\cached-request-integration-job-handler.ts:109:11)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async catchingCallbackAsync (C:\Dev\alparr-labs\homarr\packages\cron-jobs-core\src\creator.ts:38:9)
caused by TypeError: fetch failed
at fetch (C:\Dev\alparr-labs\homarr\packages\certificates\node_modules\undici\index.js:120:13)
at …
```
> feat(logs): improve logs by logging errors with causes and metadata

- packages/forms-collection/src/new-app/_form.tsx
- packages/forms-collection/src/new-app/icon-matcher.ts
Uses the debounced icon name in order to auto-populate the icon in the "Add app" form. 
Doesn't re-apply if there is already an icon selected. 
Closes #2678
> feat: implement auto-select icon

- packages/widgets/src/bookmarks/component.tsx
> fix: bookmarks layout

- apps/nextjs/src/components/layout/header/update.tsx
- apps/nextjs/src/components/layout/header/user.tsx
- apps/nextjs/src/components/user-avatar-menu.tsx
- packages/request-handler/src/update-checker.ts
<br/>
</div>
Closes #2595
In the new implementation the update check item & indicator are only loaded once github has responded. Also I've added a timeout of 10 seconds
> fix: update check blocks page loading

- packages/definitions/src/integration.ts
- packages/integrations/package.json
- packages/integrations/src/base/creator.ts
- packages/integrations/src/download-client/aria2/aria2-integration.ts
- packages/integrations/src/download-client/aria2/aria2-types.ts
- packages/integrations/src/download-client/deluge/deluge-integration.ts
- packages/integrations/src/download-client/nzbget/nzbget-integration.ts
- packages/integrations/src/download-client/qbittorrent/qbittorrent-integration.ts
- packages/integrations/src/download-client/sabnzbd/sabnzbd-integration.ts
- packages/integrations/src/download-client/transmission/transmission-integration.ts
- packages/integrations/src/index.ts
- packages/integrations/src/interfaces/downloads/download-client-items.ts
- packages/integrations/src/interfaces/downloads/download-client-status.ts
- packages/integrations/test/aria2.spec.ts
- packages/old-import/src/widgets/options.ts
- packages/translation/src/lang/en.json
- packages/widgets/src/downloads/component.tsx
- packages/widgets/src/downloads/index.ts
- pnpm-lock.yaml
<br/>
</div>
Change Logs: 
* Support Aria2 in download widget. 
* Download item detail:
* Conditional render `upspeed`, `sent` and `ratio` to torrent's item only.
* Adjust the `DownloadClientStatus` interface to support the multiple download type client such aria2.
Limitations: 
* Remove operation does not remove downloaded files (Aria2 RPC does not support this).
* The waiting and finished entries only listing first 1000 items. 
* Can only pause `downloading` and `leeching`.
* The 'error' and `completed` entries can only be removed.
> feat: Support aria2 in download widget

- apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx
- apps/nextjs/src/components/board/items/actions/create-item.ts
- packages/modals-collection/src/apps/app-select-modal.tsx
- packages/modals-collection/src/apps/index.ts
- packages/modals-collection/src/apps/quick-add-app/quick-add-app-modal.tsx
- packages/translation/src/lang/en.json
- packages/widgets/src/_inputs/widget-app-input.tsx
> [!NOTE]
>  This PR is a proposal, it is not a feature that was talked about / requested, simply a proposal of a feature to add for UX / Convenience 
Adds a "Add app" into the edit mode header directly, as a quick way to add an app to the dashboard. 
```diff
- Less generic than the "Widget" way of adding apps
- Might be confusing to add more items onto the header
- Introduces redundancy with the "wiget" way of adding an app to a dash
+ Easier/Quicker to use 
+ More visual way to quickly add an app
```
https://github.com/user-attachments/assets/eed1ca16-8309-48ac-8a64-7baf8e2b32e4
> feat: [proposal] quick add app to board

- packages/integrations/src/dashdot/dashdot-integration.ts
<br/>
</div>
I've tested this with an unmounted drive and they are being filtered out now. However, the info you get back from the dashdot API is very limited, so the whole function of mapping indexes from the /load/storage endpoint to the /info endpoint might not always be correct. But this was already there before, I only applied a filter to remove the unmounted drives and fix the available storage to display the correct info
fixes: https://github.com/homarr-labs/homarr/issues/2141
fixes: https://github.com/homarr-labs/homarr/issues/2140
> fix: calculate available space correctly and filter unmounted drives

- packages/api/src/router/integration/integration-test-connection.ts
- packages/definitions/src/integration.ts
- packages/integrations/src/media-transcoding/tdarr-integration.ts
<br/>
</div>
This is a draft PR
The API key support is fully integrated and optional during integration creation. 
The missing component is the `testConnectionAsync` function. I am running into some kind of code executing order issue. When the function is ran during integration testing, the `super.hasSecretValue("apiKey")` will return false. But whenever I skip the function and run the integration on the dashboard the API key works for Tdarr.
I found that the issue is created by using `secretKinds: [[], ["apiKey]` in `packages\definitions\src\integration.ts` to set optional secrets (this way I can make use of the existing implementation for …
> feat: add API support for Tdarr

- packages/widgets/src/releases/component.tsx
<br/>
</div>
This will improve the UI on samller widgets.
Might be good to wait for #2891 because there's some file overlap, I can merge after if needed.
https://github.com/user-attachments/assets/b3d1aad0-c6b8-4f36-baf8-0aaaff0353cd
fixes: #2953
> fix(releases-widget): improve ui for smaller widgets

- packages/common/src/cookie.ts
<br/>
</div>
Error the user got `error: URI malformed`, because of our usage of `decodeURIComponent` where any non uri encoded character with `%` throws an error. So something like `%!` -> Error, but `%20` -> `<space>`
Relevant conversation: https://discordapp.com/channels/972958686051962910/1366882564870111343/1367166436484714496 and below messages
> fix(cookie): parsing of header not working with percentage char

- packages/api/src/middlewares/integration.ts
- packages/api/src/router/docker/docker-router.ts
- packages/api/src/router/integration/integration-router.ts
- packages/api/src/router/kubernetes/router/cluster.ts
- packages/api/src/router/kubernetes/router/configMaps.ts
- packages/api/src/router/kubernetes/router/ingresses.ts
- packages/api/src/router/kubernetes/router/namespaces.ts
- packages/api/src/router/kubernetes/router/nodes.ts
- packages/api/src/router/kubernetes/router/pods.ts
- packages/api/src/router/kubernetes/router/secrets.ts
- packages/api/src/router/kubernetes/router/services.ts
- packages/api/src/router/kubernetes/router/volumes.ts
- packages/api/src/router/search-engine/search-engine-router.ts
- packages/api/src/router/widgets/calendar.ts
- packages/api/src/router/widgets/dns-hole.ts
- packages/api/src/router/widgets/downloads.ts
- packages/api/src/router/widgets/health-monitoring.ts
- packages/api/src/router/widgets/indexer-manager.ts
- packages/api/src/router/widgets/media-requests.ts
- packages/api/src/router/widgets/media-server.ts
- packages/api/src/router/widgets/media-transcoding.ts
- packages/api/src/router/widgets/network-controller.ts
- packages/api/src/router/widgets/smart-home.ts
> refactor: replace deprecated unsable_concat with concat for trpc middlewares

- packages/common/src/test/url.spec.ts
- packages/common/src/url.ts
- packages/integrations/src/unifi-controller/unifi-controller-integration.ts
<br/>
</div>
The comment on top of the port is wrong:
```js
// @ts-expect-error the URL construction is incorrect and does not append the required / at the end: https://github.com/jens-maus/node-unifi/blob/05665e8f82a900a15a9ea8b1071750b29825b3bc/unifi.js#L56, https://github.com/jens-maus/node-unifi/blob/05665e8f82a900a15a9ea8b1071750b29825b3bc/unifi.js#L95
```
Because here are the lines of code:
```js
// L56
this._baseurl = new URL(`https://${options.host}:${options.port}`);
// L95
let endpointUrl = `${this._baseurl.href}api/login`;
```
The `href` property of `URL` always return a url with trailing slash, so it does not matter if we pass a `/` …
> fix(unifi): port is ignored

- packages/widgets/src/_inputs/widget-multiReleasesRepositories-input.tsx
<br/>
</div>
---
Fixes small issue when a user tries to remove a previously added icon
> fix(releases-widget): validation preventing removal of a previously added icon

- .github/workflows/automatic-approval.yml
- .github/workflows/update-contributors.yml
- scripts/update-contributors.mjs
> ci: add update-contributors workflow

- packages/widgets/src/calendar/component.tsx
<br/>
</div>
I've tried it out locally and set my timezone to -10 where I got an offset of one day. Then I've tried a few things out and analysed the input for the day component. Finally I landed at that simple solution and tried it out again with +14, +1 and -12. Now it works as expected. Was caused by the changes of mantine v8 where we now get the date in the format `yyyy-mm-dd`.
Closes #3102
> fix(calendar): some timezones result in offset of one day

- packages/widgets/src/releases/component.tsx
<br/>
</div>
This adds hardcoded CSS class names for all elements on the releases widget.
fixes #3143
> feat(releases-widget): added hardcoded CSS class names

- apps/nextjs/src/app/[locale]/manage/integrations/_components/test-connection/test-connection-certificate.tsx
- packages/api/src/router/integration/map-test-connection-error.ts
- packages/common/src/errors/http/request-error.ts
<br/>
</div>
Related: https://discourse.pi-hole.net/t/include-ca-certificate-in-self-signed/79629
Pi-hole version 6.2+ now automatically adds the ca certificate to the returned peer certificate. So we can extract that one to trust. Sadly it only works for people that let the certificate be regenerated or that install a new pi-hole service
> feat(integrations): add support for self-signed-cert-in-chain request error

- packages/widgets/src/bookmarks/index.tsx
<br/>
</div>
https://github.com/ajnart/homarr/blob/cd78714da99e73cfdb13bd87f5474cb83756f157/src/widgets/bookmark/BookmarkWidgetTile.tsx#L51
> fix(bookmarks): wrong widget icon

- packages/widgets/src/_inputs/widget-multiReleasesRepositories-input.tsx
<br/>
</div>
This fixes a small bug, when if a provider integrations gets deleted and was preivously set against a repository release, the user will not be able to change the provider (as it would keep picking the old provider). Also improves usability because currently the user has to manually unpick a give provider to be able to pick another.
> fix(releases-widget): unable to change provider if previous is deleted

- packages/api/src/router/group.ts
<br/>
</div>
```
@homarr/nextjs:dev: 2025-08-02T13:41:39.390Z error: tRPC Error with mutation on 'group.savePermissions'
@homarr/nextjs:dev:     at Object.onError (webpack-internal:///(rsc)/./src/app/api/trpc/[trpc]/route.ts:43:67)
@homarr/nextjs:dev:     at Object.onError (webpack-internal:///(rsc)/../../node_modules/@trpc/server/dist/adapters/fetch/index.mjs:40:125)
@homarr/nextjs:dev:     at eval (webpack-internal:///(rsc)/../../node_modules/@trpc/server/dist/resolveResponse-CzlbRpCI.mjs:1969:90)
@homarr/nextjs:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
@homarr/nextjs:dev:     at async eval …
```
> fix(groups): saving permissions with none activated causes error

- apps/nextjs/src/components/layout/header.tsx
<br/>
</div>
Closes #3611 
Tried it out both with mobile & chrome devtools and no longer flashing after this change. Probably was caused by the icon text being shown for larger width
> fix(header): avatar menu flashes  when opening on mobile

- apps/nextjs/next.config.ts
- packages/widgets/src/video/component.tsx
<br/>
</div>
Closes #3912 
I've tried it out with https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 as hls stream and it worked:
> fix(video-widget): hls videos not working

- packages/integrations/src/adguard-home/adguard-home-types.ts
<br/>
</div>
Closes #3909
The field is not used anywhere and so it doesn't make sense to be part of the parse
> fix(adguard-integration): parse error with protection_disabled_duration field
